### ISSUE TITLE
Bulgarian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/bg.reactjs.org#1]
## Maintainer List

* @krasimir
* @rstankov
* @jumpalottahigh 
* @kdichev 
* @andrey-andreev 
* @ValGeorgiev 
* @deyan-a

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@krasimir) #5
* [x] Tutorial (@krasimir) #10 

### Basics

* [x] Hello World (@jumpalottahigh) #7 
* [x] Introducing JSX (@jumpalottahigh) #15 
* [x] Rendering Elements (@krasimir) #13
* [x] Components and Props (@kdichev) #17 
* [x] State and Lifecycle (@andrey-andreev) #18 
* [x] Handling Events (@jumpalottahigh) #27 
* [x] Conditional Rendering (@andrey-andreev) #22 
* [x] Lists and Keys (@krasimir) #20
* [ ] Forms (@kdichev)
* [x] Lifting State Up (@andrey-andreev) #24 
* [x] Composition vs Inheritance (@krasimir) #23
* [x] Thinking in React (@ValGeorgiev) #26 

### API Reference

* [ ] React
* [ ] React.Component (@jumpalottahigh)
* [x] ReactDOM (@ValGeorgiev) #28 
* [x] ReactDOMServer (@ValGeorgiev) #32 
* [x] DOM Elements (@deyan-a) #36
* [x] SyntheticEvent (@krasimir) #29 
* [ ] Test Utilities (@ValGeorgiev)
* [x] Shallow Renderer (@ValGeorgiev) #35 
* [x] Test Renderer (@ValGeorgiev) #33 
* [x] JS Environment Requirements (@ValGeorgiev) #34 
* [x] Glossary (@deyan-a) #50 

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@deyan-a) #206
* [ ] Add React to a Website (@deyan-a)
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited about these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@krasimir, @RStankov please use this issue to keep track of your progress!

**Comment by krasimir** [comment]
* [ ] Home Page (@krasimir)

**Comment by tesseralis** [comment]
@krasimir you should be able to edit the issue directly like so:

<img width="787" alt="screen shot 2019-02-12 at 12 46 02 pm" src="https://user-images.githubusercontent.com/1278991/52666835-2cb46b80-2ec4-11e9-8b6c-16911e119838.png">

**Comment by krasimir** [comment]
@tesseralis I think I don't have the rights to do it
![image](https://user-images.githubusercontent.com/528677/52684701-c543fd80-2f4f-11e9-9c4f-d41b93189355.png)

**Comment by tesseralis** [comment]
@krasimir you need to accept the invite to join the "reactjs" organization. Check your email! If you can't find it, let me know and I can invite you again.

**Comment by krasimir** [comment]
@tesseralis thank you for the clarification. It looks like I didn't get the email. I checked also my spam folder but there is no such email. Can you re-send the invite please.

**Comment by tesseralis** [comment]
@krasimir resent!

**Comment by krasimir** [comment]
Yep, this time it worked. Thanks!
![image](https://user-images.githubusercontent.com/528677/52697468-300a2e80-2f7a-11e9-85a2-a77330adc76f.png)

**Comment by jumpalottahigh** [comment]
Hi, all! @tesseralis I could help out with reviews (and translations) too. Could you please add me to the team?

**Comment by tesseralis** [comment]
Yup! Just submit a pull request to reactjs.org-translation and edit the bg.json file with your name on it!

**Comment by jumpalottahigh** [comment]
I'd like to work on the `Hello World` translation to get things started, could anyone add my name to it or provide edit access to the issue?

**Comment by tesseralis** [comment]
@jumpalottahigh accept the email invite to join the reactjs organization and it'll give you edit access.

**Comment by jumpalottahigh** [comment]
Thanks a ton @tesseralis !

**Comment by kdichev** [comment]
Hey, I would like to join and help out. I can start with `Components and Props`

**Comment by jumpalottahigh** [comment]
@kdichev That's awesome! Have at it!

**Comment by andrey-andreev** [comment]
Hi guys, I'll like to help with the translations too. Can I take the next page `State and Lifecycle` ?

**Comment by jumpalottahigh** [comment]
Great! All yours, @andrey-andreev :)

**Comment by andrey-andreev** [comment]
Thanks !

**Comment by kdichev** [comment]
I am taking `Forms`. Let me know if that's alright with you, guys.

**Comment by jumpalottahigh** [comment]
Just FIY, I've been and will be a bit less active in the next couple of weeks as I have too many things going on, prepping talks etc. But looking forward to contributing as soon as possible :)

**Comment by krasimir** [comment]
@jumpalottahigh no worries. Take care.

**Comment by ValGeorgiev** [comment]
Hi guys, joining to help. I will take `Thinking in React` once I am added to the organisation.

**Comment by jumpalottahigh** [comment]
Hi @ValGeorgiev and welcome! I have now reviewed and merged the PR adding you to the maintainers list. Should I add your name to the `Thinking in React` translation?

**Comment by ValGeorgiev** [comment]
Hi @jumpalottahigh, thanks for your approval. Yes, please add me to the `Thinking in React`, thank you. I don't have rights to edit this issue yet.

**Comment by deyan-a** [comment]
Hi guys,
 I'd be more than happy to join the effort and contribute to translating the docs to Bulgarian. How can I join in? I can see that the basics have been covered, so I guess I can start with the beginning of API - Reference  `React`

**Comment by jumpalottahigh** [comment]
@deyan-a Create a pull request in this repository, adding yourself in the list of the maintainers to this file - https://github.com/reactjs/reactjs.org-translation/blob/master/langs/bg.json

**Comment by ju-mihaylova** [comment]
Hi **@tesseralis**. I would like to help out with the translations. Can you please send me an invite to join the reactjs organization. Then I can take up React from the API Reference section. Thank you.

**Comment by deyan-a** [comment]
hi @ju-mihaylova , as suggested by @jumpalottahigh a post above:

> Create a pull request in this repository, adding yourself in the list of the maintainers to this file - https://github.com/reactjs/reactjs.org-translation/blob/master/langs/bg.json

**Comment by ju-mihaylova** [comment]
Hi @deyan-a, thank you for your feedback, but I am already on the list of maintainers. Is this enough to start translating or do I need to join the reactjs organization?

**Comment by jumpalottahigh** [comment]
@ju-mihaylova You can start translating and open a pull request with your translation at any time, nothing is holding you back from this. But if you also want to be a part of the organization, you do have to follow the steps above and once you've been added to the organizations, I or any of the others can add you to the Bulgarian translation team.

**Comment by kirilchristov** [comment]
Hi guys, hello from Los Angeles. I would like to join and start helping with the translation. I may start with Hooks. Although I got a newbie question. Do we have any understanding of what kind of word we do not translate (terms like 'hooks' for example?) Do we have any internal guidelines? I tried to find some but maybe I missed it. Thank you all for translating React in Bulgarian btw.  I can't wait to join.

**Comment by jumpalottahigh** [comment]
Hi @kirilchristov and thanks for the interest! To get started, create a PR in this repo by adding your name to the list: https://github.com/reactjs/reactjs.org-translation/blob/master/langs/bg.json

Regarding which words to leave off untranslated, we have a discussion and rough guidelines here:
https://github.com/reactjs/bg.reactjs.org/issues/6
We try to be as consistent as possible. Feel free to add suggestions and extend the discussion.

**Comment by d3ltaf0rc3** [comment]
Hey, guys! I'd like to help with the translation. I'm going to take the **``Add React to a Website``** page in the **``Installation``** section.

**Comment by d3ltaf0rc3** [comment]
Hey, guys! I created a PR adding myself as a maintainer. Can you add me to the organization?

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
